
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec 26 2023 12:08:19 IST (Dec 26 2023 06:38:19 UTC)

// Verification Directory fv/washing_machine_ctrl 

module washing_machine_ctrl(clk, lid, coin, cancel, mode, idle_op,
     ready_op, soak_op, wash_op, rinse_op, spin_op, coin_rtn,
     water_inlet, soak_done, wash_done, rinse_done, spin_done);
  input clk, lid, coin, cancel;
  input [1:0] mode;
  output idle_op, ready_op, soak_op, wash_op, rinse_op, spin_op,
       coin_rtn, water_inlet, soak_done, wash_done, rinse_done,
       spin_done;
  wire clk, lid, coin, cancel;
  wire [1:0] mode;
  wire idle_op, ready_op, soak_op, wash_op, rinse_op, spin_op,
       coin_rtn, water_inlet, soak_done, wash_done, rinse_done,
       spin_done;
  wire [2:0] r_reg;
  wire n_1, n_3, n_4, n_5, n_6, n_9, n_10, n_11;
  wire n_12;
  assign spin_done = 1'b0;
  assign rinse_done = 1'b0;
  assign wash_done = 1'b0;
  assign soak_done = 1'b0;
  assign water_inlet = soak_op;
  assign spin_op = 1'b0;
  assign rinse_op = 1'b0;
  DFFX1 \r_reg_reg[0] (.CLK (clk), .D (n_12), .Q (r_reg[0]), .QN (n_3));
  NOR3X0 g1017__2398(.IN1 (n_10), .IN2 (cancel), .IN3 (lid), .QN
       (n_12));
  DFFX1 \r_reg_reg[1] (.CLK (clk), .D (n_11), .Q (r_reg[1]), .QN (n_1));
  NOR3X0 g1018__5107(.IN1 (n_9), .IN2 (cancel), .IN3 (lid), .QN (n_11));
  OA22X1 g1019__6260(.IN1 (n_3), .IN2 (n_6), .IN3 (r_reg[1]), .IN4
       (n_4), .Q (n_10));
  AOI21X1 g1020__4319(.IN1 (r_reg[0]), .IN2 (n_5), .IN3 (r_reg[1]), .QN
       (n_9));
  AND2X1 g1022__8428(.IN1 (ready_op), .IN2 (cancel), .Q (coin_rtn));
  AND2X1 g1021__5526(.IN1 (n_1), .IN2 (n_5), .Q (n_6));
  NAND2X1 g1023__6783(.IN1 (n_3), .IN2 (coin), .QN (n_4));
  NOR2X0 g1024__3680(.IN1 (r_reg[1]), .IN2 (n_3), .QN (ready_op));
  NOR2X0 g1027__1617(.IN1 (n_1), .IN2 (n_3), .QN (wash_op));
  NOR2X0 g1025__2802(.IN1 (r_reg[0]), .IN2 (n_1), .QN (soak_op));
  NAND2X1 g1028__1705(.IN1 (mode[1]), .IN2 (mode[0]), .QN (n_5));
  NOR2X0 g1026__5122(.IN1 (r_reg[0]), .IN2 (r_reg[1]), .QN (idle_op));
endmodule

